//http://tms.vura.ae/
// export const BASE_URL = "http://65.1.27.14/Vura_API_Server/src/api/";
export const BASE_URL = "http://tms.vura.ae/Vura_API_Server/src/api/";
export const ADD =               `${BASE_URL}Client/add`;
export const LOGIN =             `${BASE_URL}Client/login`;
export const VERIFY_OTP =        `${BASE_URL}Client/check_otp`;
export const COUPON =            `${BASE_URL}Coupon/couponApply`;
export const GET_PROFILE =       `${BASE_URL}Client/profile`;
export const ADD_PROFILE =       `${BASE_URL}Client/add`;
export const WALLET_LIST =       `${BASE_URL}Client/wallet_list`;
export const PRODUCT_CATEGORY =  `${BASE_URL}Product/categoryList`;
export const PRODUCTS =          `${BASE_URL}Product/productCatList`;
export const WITHDRAW =          `${BASE_URL}wallet/withdrawal`;
export const WITHDRAW_HISTORY =  `${BASE_URL}wallet/transaction-history`;
export const BANK_VERIFICATION = `${BASE_URL}Client/bank-verification`;
export const NOTIFICATION =      `${BASE_URL}Notification/list`;
export const NOTIFICATION_READ = `${BASE_URL}Notification/set-read`;
export const DELETE_ACCOUNT =    `${BASE_URL}Client/client-delete`
export const POSTAL_CODE = "https://api.postalpincode.in/pincode/";
